name: HTML Validation CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run validation
        run: htmlhint index.html
